// Sydney Suburbs Data - Top 100 by population/search volume
export const suburbs = [
  // Eastern Suburbs
  { slug: 'bondi', name: 'Bondi', region: 'Eastern Suburbs', postcode: '2026', population: 11200, commonPests: ['cockroaches', 'rodents', 'ants'], description: 'Popular beachside suburb with high-density apartments prone to pest infestations.' },
  { slug: 'bondi-junction', name: 'Bondi Junction', region: 'Eastern Suburbs', postcode: '2022', population: 9800, commonPests: ['cockroaches', 'rodents', 'silverfish'], description: 'Major commercial hub with residential areas requiring regular pest management.' },
  { slug: 'randwick', name: 'Randwick', region: 'Eastern Suburbs', postcode: '2031', population: 15400, commonPests: ['termites', 'cockroaches', 'spiders'], description: 'Established suburb near bushland with diverse pest challenges.' },
  { slug: 'kingsford', name: 'Kingsford', region: 'Eastern Suburbs', postcode: '2032', population: 14200, commonPests: ['cockroaches', 'rodents', 'ants'], description: 'High-density residential area near UNSW with common urban pest issues.' },
  { slug: 'maroubra', name: 'Maroubra', region: 'Eastern Suburbs', postcode: '2035', population: 31500, commonPests: ['termites', 'cockroaches', 'spiders'], description: 'Large coastal suburb with older homes susceptible to termite damage.' },
  { slug: 'coogee', name: 'Coogee', region: 'Eastern Suburbs', postcode: '2034', population: 15800, commonPests: ['cockroaches', 'rodents', 'ants'], description: 'Beach suburb with mix of apartments and houses facing coastal pest pressures.' },
  { slug: 'double-bay', name: 'Double Bay', region: 'Eastern Suburbs', postcode: '2028', population: 4100, commonPests: ['rodents', 'possums', 'birds'], description: 'Affluent harbourside suburb requiring discreet pest management services.' },
  { slug: 'paddington', name: 'Paddington', region: 'Eastern Suburbs', postcode: '2021', population: 12400, commonPests: ['termites', 'rodents', 'cockroaches'], description: 'Heritage terrace homes with high termite risk due to timber construction.' },
  
  // Inner West
  { slug: 'newtown', name: 'Newtown', region: 'Inner West', postcode: '2042', population: 15600, commonPests: ['cockroaches', 'rodents', 'bed-bugs'], description: 'Vibrant inner-city suburb with older buildings and active pest populations.' },
  { slug: 'marrickville', name: 'Marrickville', region: 'Inner West', postcode: '2204', population: 26200, commonPests: ['termites', 'cockroaches', 'rodents'], description: 'Industrial and residential mix with warehouse conversions requiring pest inspections.' },
  { slug: 'leichhardt', name: 'Leichhardt', region: 'Inner West', postcode: '2040', population: 14800, commonPests: ['termites', 'cockroaches', 'ants'], description: 'Established Italian quarter with heritage homes and termite concerns.' },
  { slug: 'balmain', name: 'Balmain', region: 'Inner West', postcode: '2041', population: 10200, commonPests: ['termites', 'rodents', 'possums'], description: 'Historic peninsula suburb with sandstone homes and waterfront pest challenges.' },
  { slug: 'glebe', name: 'Glebe', region: 'Inner West', postcode: '2037', population: 12500, commonPests: ['cockroaches', 'rodents', 'bed-bugs'], description: 'University area with student housing and high pest turnover.' },
  { slug: 'ashfield', name: 'Ashfield', region: 'Inner West', postcode: '2131', population: 24300, commonPests: ['cockroaches', 'rodents', 'ants'], description: 'Multicultural hub with diverse food businesses requiring commercial pest control.' },
  { slug: 'summer-hill', name: 'Summer Hill', region: 'Inner West', postcode: '2130', population: 7200, commonPests: ['termites', 'cockroaches', 'spiders'], description: 'Leafy suburb with federation homes and active termite zones.' },
  { slug: 'dulwich-hill', name: 'Dulwich Hill', region: 'Inner West', postcode: '2203', population: 13100, commonPests: ['termites', 'cockroaches', 'rodents'], description: 'Residential suburb with mix of housing styles and common pest issues.' },
  
  // North Shore
  { slug: 'north-sydney', name: 'North Sydney', region: 'Lower North Shore', postcode: '2060', population: 9200, commonPests: ['cockroaches', 'rodents', 'possums'], description: 'Major CBD area with commercial and residential pest management needs.' },
  { slug: 'mosman', name: 'Mosman', region: 'Lower North Shore', postcode: '2088', population: 29500, commonPests: ['termites', 'possums', 'spiders'], description: 'Affluent harbourside suburb near bushland with diverse pest challenges.' },
  { slug: 'cremorne', name: 'Cremorne', region: 'Lower North Shore', postcode: '2090', population: 10800, commonPests: ['cockroaches', 'rodents', 'ants'], description: 'Waterfront suburb with apartment living and urban pest pressures.' },
  { slug: 'neutral-bay', name: 'Neutral Bay', region: 'Lower North Shore', postcode: '2089', population: 9400, commonPests: ['cockroaches', 'rodents', 'termites'], description: 'Bustling lower north shore suburb with mixed residential and commercial areas.' },
  { slug: 'chatswood', name: 'Chatswood', region: 'Upper North Shore', postcode: '2067', population: 25700, commonPests: ['cockroaches', 'rodents', 'ants'], description: 'Major shopping and business district with high-rise pest concerns.' },
  { slug: 'lane-cove', name: 'Lane Cove', region: 'Lower North Shore', postcode: '2066', population: 12400, commonPests: ['termites', 'possums', 'spiders'], description: 'Bushland-bordered suburb with significant termite activity.' },
  { slug: 'willoughby', name: 'Willoughby', region: 'Lower North Shore', postcode: '2068', population: 10200, commonPests: ['termites', 'cockroaches', 'ants'], description: 'Family suburb with established homes requiring termite vigilance.' },
  { slug: 'st-leonards', name: 'St Leonards', region: 'Lower North Shore', postcode: '2065', population: 8700, commonPests: ['cockroaches', 'rodents', 'ants'], description: 'Medical precinct with hospital and apartment pest management needs.' },
  
  // Northern Beaches
  { slug: 'manly', name: 'Manly', region: 'Northern Beaches', postcode: '2095', population: 16400, commonPests: ['cockroaches', 'rodents', 'termites'], description: 'Iconic beach suburb with salt air corrosion creating pest entry points.' },
  { slug: 'dee-why', name: 'Dee Why', region: 'Northern Beaches', postcode: '2099', population: 22300, commonPests: ['cockroaches', 'rodents', 'ants'], description: 'Largest Northern Beaches suburb with diverse pest management needs.' },
  { slug: 'brookvale', name: 'Brookvale', region: 'Northern Beaches', postcode: '2100', population: 8900, commonPests: ['rodents', 'cockroaches', 'ants'], description: 'Industrial area with warehouses requiring commercial pest control.' },
  { slug: 'freshwater', name: 'Freshwater', region: 'Northern Beaches', postcode: '2096', population: 8200, commonPests: ['termites', 'cockroaches', 'spiders'], description: 'Beachside suburb with older homes and termite concerns.' },
  { slug: 'mona-vale', name: 'Mona Vale', region: 'Northern Beaches', postcode: '2103', population: 9600, commonPests: ['termites', 'spiders', 'possums'], description: 'Northern beaches hub near bushland with wildlife and pest overlap.' },
  { slug: 'warriewood', name: 'Warriewood', region: 'Northern Beaches', postcode: '2102', population: 7800, commonPests: ['termites', 'spiders', 'ants'], description: 'Newer suburb with wetlands nearby attracting mosquitoes and other pests.' },
  
  // South Sydney
  { slug: 'hurstville', name: 'Hurstville', region: 'St George', postcode: '2220', population: 28400, commonPests: ['cockroaches', 'rodents', 'termites'], description: 'Major southern suburb with commercial and residential pest challenges.' },
  { slug: 'kogarah', name: 'Kogarah', region: 'St George', postcode: '2217', population: 15200, commonPests: ['cockroaches', 'rodents', 'ants'], description: 'Hospital precinct with strict pest control requirements.' },
  { slug: 'rockdale', name: 'Rockdale', region: 'St George', postcode: '2216', population: 12600, commonPests: ['cockroaches', 'rodents', 'termites'], description: 'Established suburb with mix of housing and pest pressures.' },
  { slug: 'sans-souci', name: 'Sans Souci', region: 'St George', postcode: '2219', population: 8400, commonPests: ['termites', 'mosquitoes', 'cockroaches'], description: 'Waterfront suburb with moisture-related pest issues.' },
  { slug: 'miranda', name: 'Miranda', region: 'Sutherland Shire', postcode: '2228', population: 12100, commonPests: ['termites', 'cockroaches', 'spiders'], description: 'Major Shire shopping hub with commercial and residential areas.' },
  { slug: 'cronulla', name: 'Cronulla', region: 'Sutherland Shire', postcode: '2230', population: 17900, commonPests: ['cockroaches', 'rodents', 'termites'], description: 'Beach suburb with salt damage creating pest entry points.' },
  { slug: 'sutherland', name: 'Sutherland', region: 'Sutherland Shire', postcode: '2232', population: 12800, commonPests: ['termites', 'spiders', 'possums'], description: 'Shire centre near national park with bushland pest pressures.' },
  { slug: 'caringbah', name: 'Caringbah', region: 'Sutherland Shire', postcode: '2229', population: 15200, commonPests: ['termites', 'cockroaches', 'ants'], description: 'Family suburb with established homes requiring regular inspections.' },
  
  // Inner City & CBD
  { slug: 'sydney-cbd', name: 'Sydney CBD', region: 'City', postcode: '2000', population: 18400, commonPests: ['cockroaches', 'rodents', 'bed-bugs'], description: 'Central business district with high-rise and hospitality pest challenges.' },
  { slug: 'surry-hills', name: 'Surry Hills', region: 'City', postcode: '2010', population: 17400, commonPests: ['cockroaches', 'rodents', 'bed-bugs'], description: 'Trendy inner-city suburb with restaurants and pest-prone terrace homes.' },
  { slug: 'darlinghurst', name: 'Darlinghurst', region: 'City', postcode: '2010', population: 11200, commonPests: ['cockroaches', 'rodents', 'bed-bugs'], description: 'Entertainment district with nightlife venues requiring pest management.' },
  { slug: 'potts-point', name: 'Potts Point', region: 'City', postcode: '2011', population: 12800, commonPests: ['cockroaches', 'rodents', 'bed-bugs'], description: 'High-density harbour suburb with apartment pest challenges.' },
  { slug: 'pyrmont', name: 'Pyrmont', region: 'City', postcode: '2009', population: 14600, commonPests: ['cockroaches', 'rodents', 'ants'], description: 'Waterfront precinct with new developments and pest prevention needs.' },
  { slug: 'ultimo', name: 'Ultimo', region: 'City', postcode: '2007', population: 9800, commonPests: ['cockroaches', 'rodents', 'ants'], description: 'University area with student housing and urban pest pressures.' },
  { slug: 'chippendale', name: 'Chippendale', region: 'City', postcode: '2008', population: 7600, commonPests: ['cockroaches', 'rodents', 'spiders'], description: 'Inner-city suburb with warehouses and terrace homes.' },
  { slug: 'redfern', name: 'Redfern', region: 'City', postcode: '2016', population: 13400, commonPests: ['cockroaches', 'rodents', 'bed-bugs'], description: 'Rapidly developing suburb with older housing stock.' },
  
  // Western Sydney
  { slug: 'parramatta', name: 'Parramatta', region: 'Western Sydney', postcode: '2150', population: 30200, commonPests: ['termites', 'cockroaches', 'rodents'], description: 'Second CBD with major commercial and residential pest management needs.' },
  { slug: 'liverpool', name: 'Liverpool', region: 'South Western Sydney', postcode: '2170', population: 27400, commonPests: ['termites', 'cockroaches', 'rodents'], description: 'Major south-west hub with diverse housing and pest challenges.' },
  { slug: 'penrith', name: 'Penrith', region: 'Western Sydney', postcode: '2750', population: 12800, commonPests: ['termites', 'spiders', 'rodents'], description: 'Western gateway with bushland pest pressures and termite activity.' },
  { slug: 'blacktown', name: 'Blacktown', region: 'Western Sydney', postcode: '2148', population: 47200, commonPests: ['termites', 'cockroaches', 'rodents'], description: "Sydney's largest suburb with extensive residential pest needs." },
  { slug: 'homebush', name: 'Homebush', region: 'Inner West', postcode: '2140', population: 8600, commonPests: ['termites', 'cockroaches', 'mosquitoes'], description: 'Olympic precinct with wetlands attracting mosquitoes and other pests.' },
  { slug: 'strathfield', name: 'Strathfield', region: 'Inner West', postcode: '2135', population: 11200, commonPests: ['termites', 'cockroaches', 'ants'], description: 'Leafy suburb with heritage homes and active termite zones.' },
  { slug: 'burwood', name: 'Burwood', region: 'Inner West', postcode: '2134', population: 13800, commonPests: ['cockroaches', 'rodents', 'ants'], description: 'Shopping hub with commercial and high-rise residential pest needs.' },
  { slug: 'auburn', name: 'Auburn', region: 'Western Sydney', postcode: '2144', population: 38500, commonPests: ['cockroaches', 'rodents', 'termites'], description: 'Diverse suburb with industrial and residential pest challenges.' },
  { slug: 'bankstown', name: 'Bankstown', region: 'South Western Sydney', postcode: '2200', population: 33300, commonPests: ['termites', 'cockroaches', 'rodents'], description: 'Major south-west centre with extensive pest management needs.' },
  { slug: 'campbelltown', name: 'Campbelltown', region: 'South Western Sydney', postcode: '2560', population: 31800, commonPests: ['termites', 'spiders', 'rodents'], description: 'Outer south-west city with bushland interface and termite concerns.' },
  
  // Hills District
  { slug: 'castle-hill', name: 'Castle Hill', region: 'Hills District', postcode: '2154', population: 38800, commonPests: ['termites', 'spiders', 'possums'], description: 'Major Hills suburb with bushland borders and termite hotspots.' },
  { slug: 'baulkham-hills', name: 'Baulkham Hills', region: 'Hills District', postcode: '2153', population: 38200, commonPests: ['termites', 'cockroaches', 'spiders'], description: 'Established Hills suburb with mature trees and termite activity.' },
  { slug: 'bella-vista', name: 'Bella Vista', region: 'Hills District', postcode: '2153', population: 9800, commonPests: ['termites', 'ants', 'spiders'], description: 'Newer suburb with metro access and preventive pest needs.' },
  { slug: 'kellyville', name: 'Kellyville', region: 'Hills District', postcode: '2155', population: 28400, commonPests: ['termites', 'spiders', 'possums'], description: 'Growing suburb with new homes requiring termite barriers.' },
  { slug: 'rouse-hill', name: 'Rouse Hill', region: 'Hills District', postcode: '2155', population: 21200, commonPests: ['termites', 'spiders', 'ants'], description: 'Master-planned community with bushland and pest prevention focus.' },
  
  // Additional High-Population Suburbs
  { slug: 'alexandria', name: 'Alexandria', region: 'Inner South', postcode: '2015', population: 11800, commonPests: ['cockroaches', 'rodents', 'ants'], description: 'Industrial-to-residential transition with warehouse pest challenges.' },
  { slug: 'mascot', name: 'Mascot', region: 'Inner South', postcode: '2020', population: 15200, commonPests: ['cockroaches', 'rodents', 'mosquitoes'], description: 'Airport precinct with strict commercial pest control requirements.' },
  { slug: 'zetland', name: 'Zetland', region: 'Inner South', postcode: '2017', population: 16800, commonPests: ['cockroaches', 'rodents', 'ants'], description: 'High-density development requiring building-wide pest management.' },
  { slug: 'waterloo', name: 'Waterloo', region: 'Inner South', postcode: '2017', population: 14200, commonPests: ['cockroaches', 'rodents', 'bed-bugs'], description: 'Mixed housing with public and private pest management needs.' },
  { slug: 'rosebery', name: 'Rosebery', region: 'Inner South', postcode: '2018', population: 10400, commonPests: ['cockroaches', 'rodents', 'ants'], description: 'Warehouse conversions and apartments with urban pest pressures.' },
  { slug: 'epping', name: 'Epping', region: 'Northern Sydney', postcode: '2121', population: 24600, commonPests: ['termites', 'cockroaches', 'spiders'], description: 'Major northern suburb with established trees and termite concerns.' },
  { slug: 'ryde', name: 'Ryde', region: 'Northern Sydney', postcode: '2112', population: 23400, commonPests: ['termites', 'cockroaches', 'ants'], description: 'Large northern suburb with diverse housing and pest needs.' },
  { slug: 'rhodes', name: 'Rhodes', region: 'Inner West', postcode: '2138', population: 8400, commonPests: ['cockroaches', 'rodents', 'mosquitoes'], description: 'Waterfront precinct with high-rise apartments and wetland pests.' },
  { slug: 'concord', name: 'Concord', region: 'Inner West', postcode: '2137', population: 16200, commonPests: ['termites', 'cockroaches', 'ants'], description: 'Established suburb with federation homes and termite vigilance needed.' },
  { slug: 'drummoyne', name: 'Drummoyne', region: 'Inner West', postcode: '2047', population: 11800, commonPests: ['termites', 'possums', 'cockroaches'], description: 'Harbourside suburb with older homes requiring pest inspections.' },
  
  // Additional Suburbs for Comprehensive Coverage
  { slug: 'hornsby', name: 'Hornsby', region: 'Upper North Shore', postcode: '2077', population: 21600, commonPests: ['termites', 'spiders', 'possums'], description: 'Major upper north hub bordered by national park.' },
  { slug: 'gordon', name: 'Gordon', region: 'Upper North Shore', postcode: '2072', population: 6800, commonPests: ['termites', 'cockroaches', 'possums'], description: 'Leafy upper north suburb with established gardens.' },
  { slug: 'turramurra', name: 'Turramurra', region: 'Upper North Shore', postcode: '2074', population: 12400, commonPests: ['termites', 'spiders', 'possums'], description: 'Bushland suburb with significant termite activity zones.' },
  { slug: 'pymble', name: 'Pymble', region: 'Upper North Shore', postcode: '2073', population: 11200, commonPests: ['termites', 'spiders', 'possums'], description: 'Affluent suburb with large homes and termite management needs.' },
  { slug: 'lindfield', name: 'Lindfield', region: 'Upper North Shore', postcode: '2070', population: 9800, commonPests: ['termites', 'cockroaches', 'spiders'], description: 'Family suburb with heritage homes requiring pest vigilance.' },
  { slug: 'killara', name: 'Killara', region: 'Upper North Shore', postcode: '2071', population: 8400, commonPests: ['termites', 'possums', 'spiders'], description: 'Prestigious suburb with large properties and bushland edges.' },
  { slug: 'artarmon', name: 'Artarmon', region: 'Lower North Shore', postcode: '2064', population: 9200, commonPests: ['cockroaches', 'rodents', 'ants'], description: 'Industrial and residential mix with commercial pest needs.' },
  { slug: 'crows-nest', name: 'Crows Nest', region: 'Lower North Shore', postcode: '2065', population: 8600, commonPests: ['cockroaches', 'rodents', 'ants'], description: 'Bustling village area with restaurant and cafe pest requirements.' },
  { slug: 'waverton', name: 'Waverton', region: 'Lower North Shore', postcode: '2060', population: 4200, commonPests: ['cockroaches', 'rodents', 'possums'], description: 'Harbourside suburb with apartment and townhouse pest management.' },
  { slug: 'kirribilli', name: 'Kirribilli', region: 'Lower North Shore', postcode: '2061', population: 3800, commonPests: ['cockroaches', 'rodents', 'possums'], description: 'Historic harbour suburb with heritage building pest challenges.' },
  { slug: 'milsons-point', name: 'Milsons Point', region: 'Lower North Shore', postcode: '2061', population: 4600, commonPests: ['cockroaches', 'rodents', 'ants'], description: 'High-rise harbour suburb with apartment pest management.' },
  { slug: 'lavender-bay', name: 'Lavender Bay', region: 'Lower North Shore', postcode: '2060', population: 2800, commonPests: ['cockroaches', 'possums', 'rodents'], description: 'Quiet harbourside enclave with heritage properties.' },
  { slug: 'cammeray', name: 'Cammeray', region: 'Lower North Shore', postcode: '2062', population: 8200, commonPests: ['termites', 'cockroaches', 'ants'], description: 'Family suburb with mix of apartments and houses.' },
  { slug: 'northbridge', name: 'Northbridge', region: 'Lower North Shore', postcode: '2063', population: 5400, commonPests: ['termites', 'possums', 'spiders'], description: 'Bushland suburb with significant wildlife and pest overlap.' },
  { slug: 'castle-cove', name: 'Castle Cove', region: 'Lower North Shore', postcode: '2069', population: 3200, commonPests: ['termites', 'possums', 'spiders'], description: 'Exclusive suburb bordered by bushland and harbour.' },
  { slug: 'north-ryde', name: 'North Ryde', region: 'Northern Sydney', postcode: '2113', population: 14800, commonPests: ['termites', 'cockroaches', 'ants'], description: 'Business park area with commercial and residential pest needs.' },
  { slug: 'macquarie-park', name: 'Macquarie Park', region: 'Northern Sydney', postcode: '2113', population: 8600, commonPests: ['cockroaches', 'rodents', 'ants'], description: 'Tech precinct with commercial pest management requirements.' },
  { slug: 'gladesville', name: 'Gladesville', region: 'Northern Sydney', postcode: '2111', population: 11200, commonPests: ['termites', 'cockroaches', 'ants'], description: 'Established suburb with federation homes and termite concerns.' },
  { slug: 'hunters-hill', name: 'Hunters Hill', region: 'Northern Sydney', postcode: '2110', population: 14600, commonPests: ['termites', 'possums', 'spiders'], description: 'Heritage suburb with sandstone buildings and termite vigilance.' },
  { slug: 'meadowbank', name: 'Meadowbank', region: 'Northern Sydney', postcode: '2114', population: 7200, commonPests: ['cockroaches', 'rodents', 'mosquitoes'], description: 'Waterfront suburb with high-rise developments and wetland pests.' },
  { slug: 'west-ryde', name: 'West Ryde', region: 'Northern Sydney', postcode: '2114', population: 12400, commonPests: ['termites', 'cockroaches', 'ants'], description: 'Family suburb with mix of housing styles and pest pressures.' },
  { slug: 'eastwood', name: 'Eastwood', region: 'Northern Sydney', postcode: '2122', population: 17800, commonPests: ['termites', 'cockroaches', 'rodents'], description: 'Multicultural hub with diverse food businesses and pest needs.' },
  { slug: 'carlingford', name: 'Carlingford', region: 'Northern Sydney', postcode: '2118', population: 24200, commonPests: ['termites', 'spiders', 'ants'], description: 'Family suburb with established homes and termite management.' },
];

// Pest Services Data
export const services = [
  {
    slug: 'general-pest-control',
    name: 'General Pest Control',
    shortName: 'General',
    priceRange: '$150 - $350',
    avgPrice: 250,
    description: 'Comprehensive treatment for common household pests including cockroaches, ants, spiders, and silverfish.',
    longDescription: 'General pest control is the foundation of a pest-free home. Our licensed technicians perform thorough inspections and apply targeted treatments to eliminate cockroaches, ants, spiders, silverfish, and other common pests. Treatments typically include perimeter spraying, crack and crevice treatment, baiting systems, and dusting in roof voids and subfloors.',
    commonPests: ['Cockroaches', 'Ants', 'Spiders', 'Silverfish'],
    frequency: 'Every 6-12 months',
    icon: 'bug',
    searchVolume: 8100,
  },
  {
    slug: 'termite-inspection',
    name: 'Termite Inspection',
    shortName: 'Termite Inspection',
    priceRange: '$250 - $500',
    avgPrice: 350,
    description: 'Professional timber pest inspection using thermal imaging and moisture meters to detect termite activity.',
    longDescription: 'A termite inspection is essential for protecting your biggest investment. Our licensed inspectors use state-of-the-art thermal imaging cameras, moisture meters, and Termatrac devices to detect termite activity, even behind walls. We provide a comprehensive written report detailing any findings, risk areas, and recommendations for treatment or prevention.',
    commonPests: ['Subterranean Termites', 'Drywood Termites', 'Dampwood Termites'],
    frequency: 'Annual inspection recommended',
    icon: 'search',
    searchVolume: 2400,
  },
  {
    slug: 'termite-treatment',
    name: 'Termite Treatment',
    shortName: 'Termite Treatment',
    priceRange: '$2,000 - $5,000+',
    avgPrice: 3500,
    description: 'Professional termite elimination using chemical barriers, baiting systems, or combination treatments.',
    longDescription: 'When termites are detected, swift professional treatment is crucial. We offer multiple treatment options including chemical soil barriers (Termidor, Premise, Biflex), baiting systems (Sentricon, Exterra, Nemesis), and direct colony elimination. Treatment choice depends on construction type, severity of infestation, and your property layout.',
    commonPests: ['Subterranean Termites', 'Drywood Termites'],
    frequency: 'As needed + annual monitoring',
    icon: 'shield',
    searchVolume: 1200,
  },
  {
    slug: 'rodent-control',
    name: 'Rodent Control',
    shortName: 'Rodent Control',
    priceRange: '$200 - $400',
    avgPrice: 300,
    description: 'Professional rat and mouse control including baiting, trapping, and exclusion services.',
    longDescription: 'Rodents pose serious health risks and can cause significant property damage. Our rodent control program includes identification of entry points, installation of tamper-resistant bait stations, snap traps, and exclusion work to prevent re-entry. We use second-generation anticoagulants and monitor progress over multiple visits.',
    commonPests: ['Norway Rats', 'Roof Rats', 'House Mice'],
    frequency: 'Initial treatment + monitoring',
    icon: 'mouse',
    searchVolume: 3200,
  },
  {
    slug: 'cockroach-control',
    name: 'Cockroach Control',
    shortName: 'Cockroaches',
    priceRange: '$150 - $300',
    avgPrice: 200,
    description: 'Targeted cockroach treatment using gel baits, sprays, and dusts for lasting control.',
    longDescription: 'Cockroaches are one of the most common and resilient pests in Sydney homes. Our cockroach treatment combines gel baits, residual sprays, and dusts to target all cockroach species including German, American, Australian, and Oriental cockroaches. We focus on harbourage areas in kitchens, bathrooms, and laundries.',
    commonPests: ['German Cockroaches', 'American Cockroaches', 'Australian Cockroaches'],
    frequency: 'Every 6-12 months',
    icon: 'bug',
    searchVolume: 2100,
  },
  {
    slug: 'bed-bug-treatment',
    name: 'Bed Bug Treatment',
    shortName: 'Bed Bugs',
    priceRange: '$300 - $1,500',
    avgPrice: 600,
    description: 'Specialist bed bug elimination using heat treatment, residual sprays, and mattress encasements.',
    longDescription: 'Bed bugs have made a significant comeback in Sydney, particularly in hotels, hostels, and high-density housing. Our bed bug treatment includes thorough inspection, heat treatment or residual chemical application, and ongoing monitoring. We treat mattresses, bed frames, furniture, and all cracks and crevices.',
    commonPests: ['Bed Bugs', 'Cimex lectularius'],
    frequency: 'As needed + follow-up',
    icon: 'bed',
    searchVolume: 880,
  },
  {
    slug: 'spider-control',
    name: 'Spider Control',
    shortName: 'Spiders',
    priceRange: '$150 - $300',
    avgPrice: 200,
    description: 'Professional spider treatment targeting dangerous species and reducing web buildup.',
    longDescription: 'Sydney is home to several dangerous spider species including Funnel-webs, Redbacks, and White-tails. Our spider treatment includes web removal, perimeter spraying, and targeted treatment of harbourage areas. We focus on reducing spider populations both inside and around your property.',
    commonPests: ['Funnel-web Spiders', 'Redback Spiders', 'White-tail Spiders', 'Huntsman'],
    frequency: 'Every 6-12 months',
    icon: 'bug',
    searchVolume: 1400,
  },
  {
    slug: 'ant-control',
    name: 'Ant Control',
    shortName: 'Ants',
    priceRange: '$150 - $350',
    avgPrice: 225,
    description: 'Ant colony elimination using baits and treatments that target the queen.',
    longDescription: 'Ants are social insects that require colony-level treatment for lasting control. We identify the ant species and apply targeted treatments including gel baits, granular baits, and perimeter sprays. Our approach targets the queen and nest, not just the foraging workers you see.',
    commonPests: ['Black Ants', 'Coastal Brown Ants', 'Argentine Ants', 'White-footed Ants'],
    frequency: 'Every 6-12 months',
    icon: 'bug',
    searchVolume: 1800,
  },
  {
    slug: 'possum-removal',
    name: 'Possum Removal',
    shortName: 'Possums',
    priceRange: '$200 - $800',
    avgPrice: 400,
    description: 'Humane possum removal and exclusion from roof spaces with one-way door installation.',
    longDescription: 'Possums are protected in NSW, so removal must be conducted humanely by licensed technicians. We install one-way doors allowing possums to leave but not return, then seal all entry points. We can also install possum boxes as alternative housing to discourage roof-space nesting.',
    commonPests: ['Brushtail Possums', 'Ringtail Possums'],
    frequency: 'One-time + prevention',
    icon: 'home',
    searchVolume: 720,
  },
  {
    slug: 'bird-control',
    name: 'Bird Control',
    shortName: 'Birds',
    priceRange: '$300 - $1,500',
    avgPrice: 600,
    description: 'Bird deterrent installation including spikes, netting, and wire systems.',
    longDescription: 'Pest birds like pigeons, Indian mynas, and starlings can cause significant property damage and health risks from their droppings. We install professional bird deterrent systems including stainless steel spikes, bird netting, and wire systems. We also offer cleaning and sanitisation of affected areas.',
    commonPests: ['Pigeons', 'Indian Mynas', 'Starlings', 'Sparrows'],
    frequency: 'One-time installation',
    icon: 'bird',
    searchVolume: 540,
  },
  {
    slug: 'flea-treatment',
    name: 'Flea Treatment',
    shortName: 'Fleas',
    priceRange: '$180 - $350',
    avgPrice: 250,
    description: 'Professional flea elimination for homes with pets or post-tenancy infestations.',
    longDescription: 'Flea infestations can rapidly get out of control, particularly in homes with pets. Our flea treatment targets all life stages - adults, larvae, pupae, and eggs. We treat carpets, furniture, pet bedding areas, and outdoor spaces. Pet treatment by a vet is essential for complete control.',
    commonPests: ['Cat Fleas', 'Dog Fleas'],
    frequency: 'As needed + follow-up',
    icon: 'bug',
    searchVolume: 960,
  },
  {
    slug: 'wasp-bee-removal',
    name: 'Wasp & Bee Removal',
    shortName: 'Wasps & Bees',
    priceRange: '$150 - $400',
    avgPrice: 250,
    description: 'Safe removal of wasp nests and bee swarms by licensed technicians.',
    longDescription: 'Wasp and bee nests can be dangerous, particularly for those with allergies. We safely remove wasp nests and relocate bee swarms where possible. For European wasps and paper wasps, we apply targeted treatments to eliminate the nest. Native bee relocation is handled by specialist bee keepers where available.',
    commonPests: ['European Wasps', 'Paper Wasps', 'Mud Wasps', 'Bees'],
    frequency: 'As needed',
    icon: 'bug',
    searchVolume: 680,
  },
];

// Sample Operators Data (EPA License Format)
export const operators = [
  {
    id: 1,
    slug: 'sydney-best-pest-control',
    businessName: "Sydney's Best Pest Control",
    tradingName: "Sydney's Best Pest Control Pty Ltd",
    licenseNumber: 'PMT-2024-001234',
    licenseType: 'Pest Management Technician',
    licenseStatus: 'Active',
    licenseExpiry: '2025-06-30',
    verifiedAt: '2024-11-15',
    phone: '02 9876 5432',
    email: 'info@sydneysbestpest.com.au',
    website: 'https://sydneysbestpest.com.au',
    address: '123 Main Street, Bondi NSW 2026',
    description: 'Family-owned pest control business serving the Eastern Suburbs for over 15 years. Specialists in termite inspections and treatments.',
    services: ['general-pest-control', 'termite-inspection', 'termite-treatment', 'rodent-control', 'cockroach-control'],
    serviceAreas: ['bondi', 'bondi-junction', 'randwick', 'kingsford', 'maroubra', 'coogee', 'double-bay', 'paddington'],
    rating: 4.8,
    reviewCount: 127,
    yearsInBusiness: 15,
    featured: true,
    tier: 'premium',
    badges: ['epa-verified', 'response-guarantee', 'same-day-service'],
    workingHours: {
      monday: '7:00 AM - 6:00 PM',
      tuesday: '7:00 AM - 6:00 PM',
      wednesday: '7:00 AM - 6:00 PM',
      thursday: '7:00 AM - 6:00 PM',
      friday: '7:00 AM - 6:00 PM',
      saturday: '8:00 AM - 4:00 PM',
      sunday: 'Emergency Only',
    },
    images: ['hero-1.jpg', 'work-1.jpg', 'team-1.jpg'],
    specialties: ['Termite Specialists', 'Free Quotes', 'Same Day Service'],
  },
  {
    id: 2,
    slug: 'flick-pest-control',
    businessName: 'Flick Pest Control',
    tradingName: 'Flick Anticimex Pty Ltd',
    licenseNumber: 'PMT-2024-002345',
    licenseType: 'Pest Management Technician',
    licenseStatus: 'Active',
    licenseExpiry: '2025-08-15',
    verifiedAt: '2024-11-10',
    phone: '13 14 40',
    email: 'contact@flick.com.au',
    website: 'https://flick.com.au',
    address: '456 Commercial Road, Marrickville NSW 2204',
    description: "One of Australia's largest and most trusted pest control companies. Offering comprehensive pest management solutions for homes and businesses.",
    services: ['general-pest-control', 'termite-inspection', 'termite-treatment', 'rodent-control', 'cockroach-control', 'bed-bug-treatment', 'bird-control'],
    serviceAreas: ['sydney-cbd', 'surry-hills', 'newtown', 'marrickville', 'leichhardt', 'glebe', 'ashfield', 'burwood', 'strathfield'],
    rating: 4.6,
    reviewCount: 342,
    yearsInBusiness: 100,
    featured: true,
    tier: 'enterprise',
    badges: ['epa-verified', 'response-guarantee'],
    workingHours: {
      monday: '24 Hours',
      tuesday: '24 Hours',
      wednesday: '24 Hours',
      thursday: '24 Hours',
      friday: '24 Hours',
      saturday: '24 Hours',
      sunday: '24 Hours',
    },
    images: ['flick-hero.jpg', 'flick-team.jpg'],
    specialties: ['24/7 Emergency Service', 'Commercial Specialists', 'SMART Monitoring'],
  },
  {
    id: 3,
    slug: 'abc-pest-control-sydney',
    businessName: 'ABC Pest Control Sydney',
    tradingName: 'ABC Pest Control Pty Ltd',
    licenseNumber: 'PMT-2024-003456',
    licenseType: 'Pest Management Technician',
    licenseStatus: 'Active',
    licenseExpiry: '2025-04-30',
    verifiedAt: '2024-11-12',
    phone: '02 9012 3456',
    email: 'booking@abcpestcontrol.com.au',
    website: 'https://abcpestcontrol.com.au',
    address: '789 Pest Street, North Sydney NSW 2060',
    description: "Professional pest control services across Sydney's North Shore. Specialising in eco-friendly treatments safe for families and pets.",
    services: ['general-pest-control', 'termite-inspection', 'rodent-control', 'spider-control', 'ant-control', 'possum-removal'],
    serviceAreas: ['north-sydney', 'mosman', 'cremorne', 'neutral-bay', 'chatswood', 'lane-cove', 'willoughby', 'st-leonards'],
    rating: 4.7,
    reviewCount: 89,
    yearsInBusiness: 12,
    featured: true,
    tier: 'featured',
    badges: ['epa-verified', 'same-day-service'],
    workingHours: {
      monday: '7:30 AM - 5:30 PM',
      tuesday: '7:30 AM - 5:30 PM',
      wednesday: '7:30 AM - 5:30 PM',
      thursday: '7:30 AM - 5:30 PM',
      friday: '7:30 AM - 5:30 PM',
      saturday: '8:00 AM - 2:00 PM',
      sunday: 'Closed',
    },
    images: ['abc-hero.jpg'],
    specialties: ['Eco-Friendly', 'Pet Safe', 'North Shore Specialists'],
  },
  {
    id: 4,
    slug: 'eastern-suburbs-pest-control',
    businessName: 'Eastern Suburbs Pest Control',
    tradingName: 'ESPC Services Pty Ltd',
    licenseNumber: 'PMT-2024-004567',
    licenseType: 'Pest Management Technician',
    licenseStatus: 'Active',
    licenseExpiry: '2025-09-30',
    verifiedAt: '2024-11-08',
    phone: '02 9345 6789',
    email: 'info@espestcontrol.com.au',
    website: 'https://espestcontrol.com.au',
    address: '321 Beach Road, Coogee NSW 2034',
    description: 'Local Eastern Suburbs pest control experts. We understand the unique pest challenges of coastal living.',
    services: ['general-pest-control', 'termite-inspection', 'cockroach-control', 'spider-control', 'flea-treatment'],
    serviceAreas: ['coogee', 'maroubra', 'randwick', 'kingsford', 'kensington', 'zetland', 'rosebery'],
    rating: 4.9,
    reviewCount: 67,
    yearsInBusiness: 8,
    featured: false,
    tier: 'featured',
    badges: ['epa-verified'],
    workingHours: {
      monday: '8:00 AM - 5:00 PM',
      tuesday: '8:00 AM - 5:00 PM',
      wednesday: '8:00 AM - 5:00 PM',
      thursday: '8:00 AM - 5:00 PM',
      friday: '8:00 AM - 5:00 PM',
      saturday: '9:00 AM - 1:00 PM',
      sunday: 'Closed',
    },
    images: ['espc-hero.jpg'],
    specialties: ['Coastal Pest Experts', 'Local Family Business'],
  },
  {
    id: 5,
    slug: 'termite-solutions-sydney',
    businessName: 'Termite Solutions Sydney',
    tradingName: 'TSS Pest Management Pty Ltd',
    licenseNumber: 'PMT-2024-005678',
    licenseType: 'Pest Management Technician',
    licenseStatus: 'Active',
    licenseExpiry: '2025-12-31',
    verifiedAt: '2024-11-14',
    phone: '02 9456 7890',
    email: 'enquiries@termitesolutions.com.au',
    website: 'https://termitesolutions.com.au',
    address: '555 Timber Lane, Parramatta NSW 2150',
    description: "Sydney's termite specialists. We use the latest technology including thermal imaging and Termatrac for accurate detection.",
    services: ['termite-inspection', 'termite-treatment'],
    serviceAreas: ['parramatta', 'auburn', 'homebush', 'strathfield', 'burwood', 'bankstown', 'liverpool'],
    rating: 4.8,
    reviewCount: 156,
    yearsInBusiness: 20,
    featured: true,
    tier: 'premium',
    badges: ['epa-verified', 'response-guarantee'],
    workingHours: {
      monday: '7:00 AM - 6:00 PM',
      tuesday: '7:00 AM - 6:00 PM',
      wednesday: '7:00 AM - 6:00 PM',
      thursday: '7:00 AM - 6:00 PM',
      friday: '7:00 AM - 6:00 PM',
      saturday: '8:00 AM - 3:00 PM',
      sunday: 'By Appointment',
    },
    images: ['tss-hero.jpg', 'thermal.jpg'],
    specialties: ['Termite Specialists Only', 'Thermal Imaging', '10 Year Warranties'],
  },
  {
    id: 6,
    slug: 'm-and-m-termite-pest',
    businessName: 'M&M Termite & Pest',
    tradingName: 'M&M Pest Services Pty Ltd',
    licenseNumber: 'PMT-2024-006789',
    licenseType: 'Pest Management Technician',
    licenseStatus: 'Active',
    licenseExpiry: '2025-07-15',
    verifiedAt: '2024-11-13',
    phone: '02 9567 8901',
    email: 'team@mmpest.com.au',
    website: 'https://mmpest.com.au',
    address: '888 Hills Highway, Castle Hill NSW 2154',
    description: 'Serving the Hills District and Greater Western Sydney. Family-owned business with a focus on customer service.',
    services: ['general-pest-control', 'termite-inspection', 'termite-treatment', 'rodent-control', 'possum-removal'],
    serviceAreas: ['castle-hill', 'baulkham-hills', 'bella-vista', 'kellyville', 'rouse-hill', 'penrith', 'blacktown'],
    rating: 4.7,
    reviewCount: 98,
    yearsInBusiness: 10,
    featured: false,
    tier: 'featured',
    badges: ['epa-verified', 'same-day-service'],
    workingHours: {
      monday: '7:00 AM - 5:00 PM',
      tuesday: '7:00 AM - 5:00 PM',
      wednesday: '7:00 AM - 5:00 PM',
      thursday: '7:00 AM - 5:00 PM',
      friday: '7:00 AM - 5:00 PM',
      saturday: '8:00 AM - 12:00 PM',
      sunday: 'Closed',
    },
    images: ['mm-hero.jpg'],
    specialties: ['Hills District Experts', 'Free Termite Inspections with Treatment'],
  },
  {
    id: 7,
    slug: 'green-pest-solutions',
    businessName: 'Green Pest Solutions',
    tradingName: 'GPS Eco Pest Control Pty Ltd',
    licenseNumber: 'PMT-2024-007890',
    licenseType: 'Pest Management Technician',
    licenseStatus: 'Active',
    licenseExpiry: '2025-05-31',
    verifiedAt: '2024-11-11',
    phone: '02 9678 9012',
    email: 'hello@greenpestsolutions.com.au',
    website: 'https://greenpestsolutions.com.au',
    address: '100 Eco Drive, Manly NSW 2095',
    description: 'Eco-conscious pest control using organic and low-toxicity treatments. Safe for your family, pets, and the environment.',
    services: ['general-pest-control', 'ant-control', 'spider-control', 'flea-treatment', 'wasp-bee-removal'],
    serviceAreas: ['manly', 'dee-why', 'brookvale', 'freshwater', 'mona-vale', 'warriewood'],
    rating: 4.6,
    reviewCount: 54,
    yearsInBusiness: 6,
    featured: false,
    tier: 'basic',
    badges: ['epa-verified'],
    workingHours: {
      monday: '8:00 AM - 5:00 PM',
      tuesday: '8:00 AM - 5:00 PM',
      wednesday: '8:00 AM - 5:00 PM',
      thursday: '8:00 AM - 5:00 PM',
      friday: '8:00 AM - 5:00 PM',
      saturday: 'By Appointment',
      sunday: 'Closed',
    },
    images: ['green-hero.jpg'],
    specialties: ['100% Eco-Friendly', 'Organic Options', 'Northern Beaches'],
  },
  {
    id: 8,
    slug: 'pro-pest-management',
    businessName: 'Pro Pest Management',
    tradingName: 'Pro Pest Management Sydney Pty Ltd',
    licenseNumber: 'PMT-2024-008901',
    licenseType: 'Pest Management Technician',
    licenseStatus: 'Active',
    licenseExpiry: '2025-10-31',
    verifiedAt: '2024-11-09',
    phone: '02 9789 0123',
    email: 'bookings@propestmanagement.com.au',
    website: 'https://propestmanagement.com.au',
    address: '200 Industrial Ave, Alexandria NSW 2015',
    description: 'Commercial and industrial pest control specialists. HACCP certified for food processing environments.',
    services: ['general-pest-control', 'rodent-control', 'cockroach-control', 'bird-control', 'bed-bug-treatment'],
    serviceAreas: ['sydney-cbd', 'alexandria', 'mascot', 'zetland', 'waterloo', 'rosebery', 'pyrmont', 'ultimo'],
    rating: 4.5,
    reviewCount: 73,
    yearsInBusiness: 18,
    featured: true,
    tier: 'premium',
    badges: ['epa-verified', 'response-guarantee'],
    workingHours: {
      monday: '24 Hours',
      tuesday: '24 Hours',
      wednesday: '24 Hours',
      thursday: '24 Hours',
      friday: '24 Hours',
      saturday: '24 Hours',
      sunday: '24 Hours',
    },
    images: ['pro-hero.jpg', 'commercial.jpg'],
    specialties: ['Commercial Specialists', 'HACCP Certified', '24/7 Service'],
  },
  {
    id: 9,
    slug: 'southern-sydney-pest-control',
    businessName: 'Southern Sydney Pest Control',
    tradingName: 'SSPC Pty Ltd',
    licenseNumber: 'PMT-2024-009012',
    licenseType: 'Pest Management Technician',
    licenseStatus: 'Active',
    licenseExpiry: '2025-11-30',
    verifiedAt: '2024-11-07',
    phone: '02 9890 1234',
    email: 'info@southernsydneypest.com.au',
    website: 'https://southernsydneypest.com.au',
    address: '45 Shire Road, Sutherland NSW 2232',
    description: 'Trusted pest control for the Sutherland Shire and St George areas. Local knowledge of coastal and bushland pest challenges.',
    services: ['general-pest-control', 'termite-inspection', 'termite-treatment', 'spider-control', 'possum-removal'],
    serviceAreas: ['hurstville', 'kogarah', 'rockdale', 'sans-souci', 'miranda', 'cronulla', 'sutherland', 'caringbah'],
    rating: 4.8,
    reviewCount: 112,
    yearsInBusiness: 14,
    featured: true,
    tier: 'featured',
    badges: ['epa-verified', 'same-day-service'],
    workingHours: {
      monday: '7:00 AM - 5:30 PM',
      tuesday: '7:00 AM - 5:30 PM',
      wednesday: '7:00 AM - 5:30 PM',
      thursday: '7:00 AM - 5:30 PM',
      friday: '7:00 AM - 5:30 PM',
      saturday: '8:00 AM - 2:00 PM',
      sunday: 'Emergency Only',
    },
    images: ['sspc-hero.jpg'],
    specialties: ['Shire Specialists', 'Bushfire Zone Experience', 'Same Day Service'],
  },
  {
    id: 10,
    slug: 'inner-west-pest-services',
    businessName: 'Inner West Pest Services',
    tradingName: 'IWPS Pty Ltd',
    licenseNumber: 'PMT-2024-010123',
    licenseType: 'Pest Management Technician',
    licenseStatus: 'Active',
    licenseExpiry: '2025-03-31',
    verifiedAt: '2024-11-06',
    phone: '02 9901 2345',
    email: 'contact@innerwestpest.com.au',
    website: 'https://innerwestpest.com.au',
    address: '78 King Street, Newtown NSW 2042',
    description: 'Your local Inner West pest experts. We specialize in terrace homes and apartment buildings.',
    services: ['general-pest-control', 'termite-inspection', 'rodent-control', 'cockroach-control', 'bed-bug-treatment'],
    serviceAreas: ['newtown', 'marrickville', 'leichhardt', 'balmain', 'glebe', 'ashfield', 'summer-hill', 'dulwich-hill'],
    rating: 4.7,
    reviewCount: 86,
    yearsInBusiness: 9,
    featured: false,
    tier: 'featured',
    badges: ['epa-verified'],
    workingHours: {
      monday: '8:00 AM - 6:00 PM',
      tuesday: '8:00 AM - 6:00 PM',
      wednesday: '8:00 AM - 6:00 PM',
      thursday: '8:00 AM - 6:00 PM',
      friday: '8:00 AM - 6:00 PM',
      saturday: '9:00 AM - 3:00 PM',
      sunday: 'Closed',
    },
    images: ['iwps-hero.jpg'],
    specialties: ['Terrace Home Experts', 'Strata Specialists', 'Inner West Local'],
  },
];

// Reviews Data
export const reviews = [
  { id: 1, operatorId: 1, author: 'Sarah M.', suburb: 'Bondi', rating: 5, date: '2024-11-10', text: 'Excellent service! They found termite activity that another company missed. Very thorough inspection using thermal camera.' },
  { id: 2, operatorId: 1, author: 'James L.', suburb: 'Randwick', rating: 5, date: '2024-10-28', text: 'Quick response, professional team. They explained everything clearly and the treatment worked perfectly.' },
  { id: 3, operatorId: 1, author: 'Michelle K.', suburb: 'Coogee', rating: 4, date: '2024-10-15', text: 'Good service overall. A bit pricey but you get what you pay for with quality pest control.' },
  { id: 4, operatorId: 2, author: 'David W.', suburb: 'Sydney CBD', rating: 5, date: '2024-11-12', text: 'Our office building has been using Flick for years. Always reliable, always professional.' },
  { id: 5, operatorId: 2, author: 'Lisa T.', suburb: 'Marrickville', rating: 4, date: '2024-10-30', text: 'Great response time for our emergency cockroach situation. Would recommend.' },
  { id: 6, operatorId: 3, author: 'Peter H.', suburb: 'Mosman', rating: 5, date: '2024-11-08', text: 'Love that they use eco-friendly products. Safe for my kids and pets!' },
  { id: 7, operatorId: 4, author: 'Emma R.', suburb: 'Maroubra', rating: 5, date: '2024-11-05', text: 'Local business that really knows our area. Great communication throughout.' },
  { id: 8, operatorId: 5, author: 'Chris B.', suburb: 'Parramatta', rating: 5, date: '2024-11-11', text: 'Found extensive termite damage. Their treatment and repair recommendations saved our home.' },
];

// FAQ Data for SEO
export const faqs = {
  general: [
    { question: 'How much does pest control cost in Sydney?', answer: 'General pest control in Sydney typically costs $150-$350 for a standard 3-4 bedroom home. Termite inspections range from $250-$500, while termite treatments can cost $2,000-$5,000+ depending on the property size and treatment method required.' },
    { question: 'How often should I get pest control done?', answer: 'For general pest control, we recommend treatment every 6-12 months. For termite inspections, annual inspections are essential, especially for homes in high-risk areas or those without physical barriers.' },
    { question: 'Are pest control chemicals safe for pets and children?', answer: 'Modern pest control products are designed to be low-toxicity when applied correctly by licensed technicians. We recommend keeping pets and children away from treated areas until dry (usually 1-2 hours). Many operators offer eco-friendly options for sensitive environments.' },
    { question: 'How long does a pest control treatment take?', answer: 'A general pest control treatment typically takes 30-60 minutes for a standard home. Termite inspections take 1-2 hours depending on property size and access. Termite treatments can take 1-3 days depending on the method used.' },
    { question: 'Do I need to leave my home during pest control?', answer: 'For most general pest treatments, you can remain home but should stay out of treated areas until dry. For fumigation treatments (rare in residential settings), you will need to vacate for 24-72 hours.' },
  ],
  termites: [
    { question: 'How do I know if I have termites?', answer: 'Signs of termite activity include: mud tubes on walls or foundations, hollow-sounding timber, bubbling or cracked paint, frass (termite droppings), discarded wings near windows/doors, and tight-fitting doors or windows. If you notice any of these signs, arrange a professional inspection immediately.' },
    { question: 'How much does termite treatment cost in Sydney?', answer: 'Termite treatment costs vary based on property size, construction type, and treatment method. Chemical barriers typically cost $2,000-$4,000 for an average home. Baiting systems cost $2,500-$5,000+ for installation and ongoing monitoring.' },
    { question: 'What is the best termite treatment method?', answer: 'The best method depends on your property. Chemical barriers (Termidor, Premise) are excellent for perimeter protection. Baiting systems (Sentricon, Exterra) are ideal for colony elimination and ongoing monitoring. Many properties benefit from a combination approach.' },
    { question: 'Does home insurance cover termite damage?', answer: 'Most Australian home insurance policies do NOT cover termite damage as it is considered preventable through regular inspections. This is why annual termite inspections are so important—prevention is far cheaper than repair.' },
  ],
};

// Helper Functions
export function getSuburbBySlug(slug) {
  return suburbs.find(s => s.slug === slug);
}

export function getServiceBySlug(slug) {
  return services.find(s => s.slug === slug);
}

export function getOperatorBySlug(slug) {
  return operators.find(o => o.slug === slug);
}

export function getOperatorsForSuburb(suburbSlug) {
  return operators.filter(o => o.serviceAreas.includes(suburbSlug));
}

export function getOperatorsByService(serviceSlug) {
  return operators.filter(o => o.services.includes(serviceSlug));
}

export function getReviewsForOperator(operatorId) {
  return reviews.filter(r => r.operatorId === operatorId);
}

export function getSuburbsByRegion(region) {
  return suburbs.filter(s => s.region === region);
}

export function getFeaturedOperators() {
  return operators.filter(o => o.featured);
}

export function getRegions() {
  return [...new Set(suburbs.map(s => s.region))];
}
